# s= input()
# s=s.strip()  
# s=" ".join(s.split())  
# s=s.capitalize()  
# s=s.replace(" ,", ",")  
# s=s.replace(" ;", ";")  
# s=s.replace(" :", ":")  
# s=s.replace(" .", ".")  
# print(s)
# n=input('')
# n=n.strip()
# n=' '.join(n.split())
# n=n.lower()
# n=n.capitalize()
# for i in [',',';',':','.']:
#     n=n.replace(' '+ i, i)
# print(n)