#a=input("Ho ten: ")
#b=int(input('So ngay cong: '))
#c=float(input('Don gia ngay cong: '))
#d=float(input('He so phu cap: '))
#e=int(input('Tam ung: '))
#f=float(int(c*b*d))
#g=float(int(f-e))
#print('Nhan vien '+str(a)+",",'Co tien Luong='+str(f)+', Tam ung='+str(e)+' va Thuc linh= '+str(g))
a=input('Ho ten:')
b=int(input('So ngay cong:'))
c=float(input('Don gia ngay cong:'))
d=float(input('He so phu cap'))
e=float(input('Tam ung:'))
f=round(float(c*b*d),1)
g=round(float(f-e),1)
print('Nhan vien', a ,'Co tien Luong=',f,'Tam ung=',e,'va Thuc linh=',g)